### ISSUE TITLE
Tagging other users in a comment

### ISSUE THREAD

**Issue by RandomlyKnighted** [jonan/ForkHub#100]
Is it possible to get a list of all users who have commented on an issue (including the user who created the issue)? If so I'd like to request a new feature where if you type @ then a list of users associated with that issue (or PR) shows up so you can tag them in your comment.

**Comment by jonan** [comment]
There's no API for getting the list of users you want, but we have the comments, so it shouldn't be to hard to create the list ourself.

The complex part is the actual UI for it.

Anyhow, this issue is the same as #55
