### ISSUE TITLE
Cant see pull requests

### ISSUE THREAD

**Issue by SweBeat** [jonan/ForkHub#104]
I've had two pull requests open but none of them show up when I go into the project on the app to look. I see in the "news" section that people been commenting on them but I can't see them when going into pull requests

**Comment by jonan** [comment]
Can you tell me in which repo are you having this problems so I can look into it?

**Comment by SweBeat** [comment]
Hi, sorry,

Here is the link to the repo: https://github.com/Wox-launcher/Wox

**Comment by jonan** [comment]
I can see your PR under the 'issues' tab. Where do you expect to see it?

**Comment by SweBeat** [comment]
I can see them online, but in the android app I can't see anything under either issues or pull requests.

**Comment by jonan** [comment]
I can see your pull requests perfectly:

![device-2015-11-26-120214](https://cloud.githubusercontent.com/assets/1110193/11421492/97ab3536-9435-11e5-948d-bc927b5d0de4.png)

I have to filter by closed issues now, but I saw them when they were open too.

**Comment by jonan** [comment]
@SweBeat is this the same issue as #106?

**Comment by SweBeat** [comment]
Yep. Exactly the same. 

Den 27 nov. 2015 20:35 skrev Jon Ander Peñalba <notifications@github.com>:

@SweBeat is this the same issue as #106?
