### ISSUE TITLE
Can't see issues reported in third party repo in my dashboard

### ISSUE THREAD

**Issue by sbaconnais** [jonan/ForkHub#106]
I opened some bugs in repositories I don't own and I can't find them on forkhub ( I can on octodroid).

**Comment by jonan** [comment]
Can you tell me what repo are you having troubles with?

Might be related to #104

**Comment by sbaconnais** [comment]
Sure jonan/ForkHub, theScrabi/NewPipe, DF1E/SimpleExplorer, Etuldan/spaRSS, ...

Impossible to find the tickets I opened in ForkHub (or GitHub android) even if I can see it on octodroidr.

**Comment by jonan** [comment]
You can't see your issues or you can't see any issue? Can you please send a screenshot?

It seams really weird...

**Comment by sbaconnais** [comment]
I can see issues of my own repositories, not issues of other repositories, even if I'm the creator of the issue.

**Comment by jonan** [comment]
I have no problems seeing your issues:

![device-2015-11-26-190517](https://cloud.githubusercontent.com/assets/1110193/11429964/87f9fca4-947f-11e5-88ce-4334cafb9454.png)

**Comment by sbaconnais** [comment]
I mean i can't find  my issues in the tickets overview

**Comment by sbaconnais** [comment]
![screenshot_2015-11-26-21-45-08](https://cloud.githubusercontent.com/assets/5074414/11430882/9b8a2b28-948d-11e5-8ad5-e282d687dabf.png)

**Comment by jonan** [comment]
This has been discussed in https://github.com/pockethub/PocketHub/issues/312, I'm not really sure if we should consider this a bug.

I'll think about it and try to find a solution.

**Comment by sbaconnais** [comment]
Ok thanks :)

**Comment by Nosthertus** [comment]
I also have this issue. I cant see the issues i created or commented in other repositories.

**Comment by malenki** [comment]
It would be nice to see the issues one created on other repos as well. 
Being not a coder but a quite active reporter on several repositories it would be nice to manage the issues in the app as well as using a browser.
The PocketHub issue linked above mentions this API call; probably it is helpful:
https://api.github.com/search/issues?q=author:malenki

**Comment by jonan** [comment]
I added a few changes to the issue dashboard in the last release that should make it similar to what you see in https://github.com/issues
