### ISSUE TITLE
PowerShell files missing syntax highlighting

### ISSUE THREAD

**Issue by RandomlyKnighted** [jonan/ForkHub#110]
There is no syntax highlighting for ```.ps1``` and ```.psm1``` files. For example: [.ps1](https://github.com/NARKOZ/hacker-scripts/blob/master/powershell/smack_my_bitch_up.ps1) and [.psm1](https://github.com/NARKOZ/hacker-scripts/blob/master/powershell/hangover.psm1)

**Comment by jonan** [comment]
This is really an issue with https://github.com/codemirror/CodeMirror (the library we use for code highlighting). If you want to see it fixed, you should report it there.

**Comment by RandomlyKnighted** [comment]
[Done](https://github.com/codemirror/CodeMirror/issues/3898}.

When the support is added will anything have to be done to ForkHub in order to support the change?

**Comment by jonan** [comment]
Simply upgrade the used version.

**Comment by RandomlyKnighted** [comment]
@jonan My request on their repo was closed. They pointed me to their mode request list which if you go down to the PowerShell section just says to [fork this](https://github.com/VapidWorx/powershell-cm-mode).

**Comment by jonan** [comment]
Guess it's not that simple to implement. Not much we can do on our side unfortunately...

**Comment by RandomlyKnighted** [comment]
How are you utilizing CodeMirror? Are you just using their JS files?

**Comment by jonan** [comment]
Yes, they are copied to `app/src/main/assets`

**Comment by RandomlyKnighted** [comment]
Alright, then it might be possible to add the [powershell.js](https://github.com/VapidWorx/powershell-cm-mode/blob/master/powershell.js) file to the assets folder. I'm not sure if anything else would have to be done in order to enable it once it's added.

**Comment by jonan** [comment]
I don't think so.
The last commit to that repository was three years ago, CodeMirror was in version 3.14.0 back then and we are currently using v5.13.0.
There's probably a reason why it hasn't been merged upstream.

**Comment by jonan** [comment]
We might be able to use https://github.com/ajaxorg/ace, the syntax highlighter used by GitHub.
I'll look at it and balance the pros and cons.

**Comment by RandomlyKnighted** [comment]
Awesome, thanks!

**Comment by jonan** [comment]
CodeMirror has added PowerShell syntax highlighting to the latest release, so this issue can be closed.

I've opened a new one to take a look at using Ace #194
