### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by amitsahni** [jonan/ForkHub#119]
I dont see any option from where i can logout from this app and login with some other account. Please help..

**Comment by jonan** [comment]
We are still missing a logout button, if you want to logout you need to remove the account manually through your device's settings.

The logout functionality is planned and so is the multiple account support #51

**Comment by klorinczi** [comment]
+1

**Comment by webmaster33** [comment]
I also miss the logout feature. This is a minimum feature, which is required!

**Comment by jonan** [comment]
@webmaster33 PR welcome :wink:
