### ISSUE TITLE
Avoid -SNAPSHOT dependencies

### ISSUE THREAD

**Issue by krt16s** [jonan/ForkHub#126]
Using SNAPSHOT versions of dependencies makes it tricky to figure out which version to build with. If you really have to do it, it would be nice to have the corresponding commit hash of upstream written down.

**Comment by jonan** [comment]
Yes, it's a bad practice, but needed in this case for the release.

Egit GitHub sees very little activity lately, and each release has only a few commits (most of the mine), so a snapshot is almost the same as the final release and shouldn't affect the build.

I'll remove it ASAP.
