### ISSUE TITLE
Wiki missing? 

### ISSUE THREAD

**Issue by Fohlen** [jonan/ForkHub#127]
At least for me it is not possible to view the wiki of a repository within forkhub.

**Comment by RandomlyKnighted** [comment]
It's that way for everyone.

**Comment by vjandrea** [comment]
+1 it would be quite useful, also because on Android GitHub links defaulted to ForkHub catch wiki links too, obviously displaying nothing

**Comment by rugk** [comment]
:+1:

**Comment by jonan** [comment]
There is no API to get the content of a wiki, so I can't add full support for them.
Anyhow, the app no longer catches links to wiki pages and I'll add a button in the menu to open the repos' wiki in a browser.

**Comment by Fohlen** [comment]
Since the wiki will not anytime soon be supported by the GitHub API it is probably best to close this issue.
We had it for a while mirroring our wiki with `git pull --mirror` but that's an insane amount of work just to get the GitHub API to render wiki pages.

**Comment by ghost** [comment]
Oh my God.. GitHub have really not added this to the API yet? Must be a reason.
