### ISSUE TITLE
Last version not yet on F-droid

### ISSUE THREAD

**Issue by noisnogit** [jonan/ForkHub#132]
The version on F-droid is slightly behind the play store one. Could you please upload the new source code?

**Comment by jonan** [comment]
The source code is uploaded.
The version on F-Droid hasn't been updated because it uses unreleased dependencies #126

**Comment by noisnogit** [comment]
Oh, thanks for your prompt response. :)

**Comment by jonan** [comment]
F-Droid's version is up to date now :+1:

**Comment by noisnogit** [comment]
\o/ Thanks!
