### ISSUE TITLE
Private repositories not visible

### ISSUE THREAD

**Issue by sedrubal** [jonan/ForkHub#138]
I think private repositories are not visible in organizations even when you're logged in and have access to them.

**Comment by jonan** [comment]
I can see the private repositories of all the organizations I'm in, and they all appear in my repositories tab.
Have you tried refreshing the view?

**Comment by sedrubal** [comment]
Ehm you're right but in the repository list of the organization they are only listed under "recently viewed" but not under their letter. Maybe that's why I was confused.

**Comment by jonan** [comment]
Each repository will only appear once, if you have them in the "recently viewed" list, they wont appear again under their letter.

**Comment by sedrubal** [comment]
Ok, thanks and sorry ;)
