### ISSUE TITLE
Code browser refresh issue

### ISSUE THREAD

**Issue by neilscudder** [jonan/ForkHub#142]
After using git mv to rename a file in a sub-directory, and confirming the change in the commits panel, the directory listing did not refresh until after exiting and re-loading the whole repo. It seems that the file listing does not refresh except on loading of the repo.

**Comment by jonan** [comment]
Did you press the `refresh` button? That should force a refresh.

I need to implement the `pull-to-refresh` feature in that view, but refreshing is possible.
