### ISSUE TITLE
Copy, paste, cut icons have bad contrast

### ISSUE THREAD

**Issue by theScrabi** [jonan/ForkHub#143]
The Icons for copy, paste, and cut are hardly visible.

![screenshot_2016-02-05-02-14-45](https://cloud.githubusercontent.com/assets/1891273/12875792/d1f66896-cdf1-11e5-97ad-5804b65c242c.png)

**Comment by jonan** [comment]
What Android version are you using?

**Comment by theScrabi** [comment]
Its android 4.4.4.

**Comment by jonan** [comment]
This is fixed in master. Thanks!
