### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by amilopowers** [jonan/ForkHub#146]
None of the information is updating. All the other apps do work. Even when I trigger a reload manaully it wont update. I use the latest version from f-droid on my Nexus 5.

**Comment by jonan** [comment]
This issue doesn't provide much information and I don't know of anyone that has experienced anything similar.

Are you sure you had a working Internet connection when this happened?

**Comment by amilopowers** [comment]
I use a Nexus 5 with Android 6.0.1. the weird thing is that the app doesn't ask the permission to access the internet. Only contacts.

**Comment by amilopowers** [comment]
And yes it does have internet access because I am writing this in that very app.

**Comment by jonan** [comment]
I'm also using a Nexus 5 with Android 6.0.1.

What exactly isn't being updated?

**Comment by amilopowers** [comment]
For example in the error overview there are no errors at all. I opened several in different repos. But everything else as well. The main view was last updated in December.

**Comment by amilopowers** [comment]
I am trying to get a logcat tonight.

**Comment by bcu8heq2** [comment]
Same problem here. Xperia Z1 Compact. Android 4.4.4.

**Comment by jonan** [comment]
@bcu8heq2 You can't currently see your starred repos, only the repos you follow #66

**Comment by jonan** [comment]
Not much information on this issue and no one else has complaint about not seeing updates.

Please reopen if the issue persist or if you can add more information.
