### ISSUE TITLE
Purple color to match GitHub's nuances

### ISSUE THREAD

**Issue by DaniellMesquita** [jonan/ForkHub#151]

**Comment by jonan** [comment]
Duplicate #112

**Comment by DaniellMesquita** [comment]
This is not a duplicate, but an uneeded change since user will can use preference color accourding to #112. My suggestion is not to user can change colors, but purple color as default instead of blue.This isn't a duplicate ;)

**Comment by jonan** [comment]
I know, but I don't want to change the default color to purple, so the only way this feature could be added is if #112 is implemented.
