### ISSUE TITLE
Make search history editable

### ISSUE THREAD

**Issue by sedrubal** [jonan/ForkHub#16]
Can you make the search history editable:

If I searched `foo` before and now I want to search `foo bar` I'd find it nice, if I could tab on `search icon` and then on `foo` and add ` bar` and then press the search button to search.

**Comment by sedrubal** [comment]
thank you for implementing :)

Actually I wanted to explain, that tapping on a suggestion not starts the search but inserts the suggestion into the search bar. But this is ok anyway.

**Comment by jonan** [comment]
Ok, I see what you mean now, but I think the current behavior is enough.
You'll normally want to edit your last search, and if you click an older search you'll normally want to repeat it.

**Comment by sedrubal** [comment]
OK. Sorry for the bad explanation...
