### ISSUE TITLE
Context menu text appears white on white background. 

### ISSUE THREAD

**Issue by hydroid7** [jonan/ForkHub#162]
As above. My device is a kazam tornado 348. It's running on Android 4.4.2
Link: http://s23.postimg.org/sjkfip3p7/Screenshot_2016_03_04_08_46_35.png

**Comment by jonan** [comment]
What Android version are you using?

Probably related to #143

**Comment by jonan** [comment]
Is this fixed in the latest release?

**Comment by hydroid7** [comment]
If you use the ... Button in the right corner, it's ok. But if I use the
physical button, the bug is present.
Am 12.04.2016 14:07 schrieb "Jon Ander Peñalba" <notifications@github.com>:

**Comment by jonan** [comment]
Sorry @hydroid7, but the last version where I can reproduce this issue is `v1.1.0`.
Are you sure you're running the latest release?

**Comment by hydroid7** [comment]
Well sorry you re right, after update the bug is not present!
Am 12.04.2016 15:50 schrieb "Jon Ander Peñalba" <notifications@github.com>:

**Comment by jonan** [comment]
Thanks for the update :+1:
