### ISSUE TITLE
Update iconography

### ISSUE THREAD

**Issue by nwalters512** [jonan/ForkHub#165]
This issue has several components; they can be broken into separate issues for further discussion if needed, but they're all linked, so I'm going to start by grouping them into this one issue.

First, I think the policy of using strictly GitHub icons isn't the best. I understand it for GitHub-specific concepts, like forks, gists, and bookmarks. However, for other concepts, like "search", "add", "comment", and "save", I don't see a particular reason to favor GitHub's icons over those provided by Google. Both GitHub's and Google's icons are very similar, and using Google's would definitely help the app feel more native to Android.

Second, all of the icons with name of the form `menu_*.png` are neither GitHub specific icons, or their modern Material equivalents. We should be able to update these without issue. However, most of them seem to be used only in menu items with `showAsAction` set to `never`, so the icons are never actually displayed. These should probably be removed to shrink APK size a bit.

Third, for the GitHub octicon icons that are used throughout the app, we should update those to include `xxhdpi` and `xxxhdpi` sizes and re-render them in opaque white (or black, for the navigation drawer) so that they fit in with existing iconography better.

**Comment by jonan** [comment]
> First, I think the policy of using strictly GitHub icons isn't the best. I understand it for GitHub-specific concepts, like forks, gists, and bookmarks. However, for other concepts, like "search", "add", "comment", and "save", I don't see a particular reason to favor GitHub's icons over those provided by Google. Both GitHub's and Google's icons are very similar, and using Google's would definitely help the app feel more native to Android.

I'll rather use GitHub icons whenever possible to maintain consistency across the app. I agree that following Android's design guidelines is important, but as you've mentioned, the icons are pretty similar, so it's kind of hard to distinguish them unless you see them together.
Anyhow, this is not set on stone, we can discuss it on an icon basis if we find a Material Design icon that is best suited for certain action. Also, some actions don't have a GitHub icon representing them, in this case using a Material Design one is perfectly fine.

> Second, all of the icons with name of the form `menu_*.png` are neither GitHub specific icons, or their modern Material equivalents. We should be able to update these without issue. However, most of them seem to be used only in menu items with `showAsAction` set to `never`, so the icons are never actually displayed. These should probably be removed to shrink APK size a bit.

I agree, most of this icons should probably be removed, and the ones that are really being used, should be updated.

> Third, for the GitHub octicon icons that are used throughout the app, we should update those to include `xxhdpi` and `xxxhdpi` sizes and re-render them in opaque white (or black, for the navigation drawer) so that they fit in with existing iconography better.

Actually, I was planing on using the new `support-vector-drawable` library to use vector images and support all the screen densities. I still need to try this approach, but I think it's promising.

**Comment by nwalters512** [comment]
>  but as you've mentioned, the icons are pretty similar, so it's kind of hard to distinguish them unless you see them together.

I guess I've spent too much time staring at Android apps, I noticed the icons weren't quite right immediately (especially search and add) :stuck_out_tongue:

> I agree, most of this icons should probably be removed, and the ones that are really being used, should be updated.

I'll put in a PR for this soon.

> Actually, I was planing on using the new support-vector-drawable library to use vector images and support all the screen densities. I still need to try this approach, but I think it's promising.

That would definitely be ideal. The issue there is that all the Octicons that this would be relevant to seem to be used only in menus, and from a brief glance at the Support Lib documentation, it looks like vector drawables aren't yet supported automatically in menus. That would mean either (a) manually setting the drawable of each menu item with an icon, or (b) having Android Studio generate density-specific PNGs from the vector source. (a) would let us keep the benefits of using vector drawables (mostly space savings) at the expense of harder-to-maintain code, whereas (b) would be easy to maintain, but would be essentially what already exists, with the benefit that adding/changing icons would be easier.

**Comment by jonan** [comment]
>I guess I've spent too much time staring at Android apps, I noticed the icons weren't quite right immediately (especially search and add) :stuck_out_tongue:

I've been thinking about it, and I think we can use Material Design icons for the Toolbar actions. Most of them don't have a proper representation in GitHub's icon set and I agree it makes the app look more consistent in Android.

**Comment by jonan** [comment]
I think all the issues that are mentioned here have already been addressed. Is there anything more that you feel needs to be done?

**Comment by nwalters512** [comment]
No, I think everything looks good now. Thanks for agreeing to make this change!
