### ISSUE TITLE
Show merge status for PRs

### ISSUE THREAD

**Issue by RandomlyKnighted** [jonan/ForkHub#169]
On the GitHub website, when you view a PR the site tells you if you're able to merge the PR or if there is a merge conflict. It would be great ForkHub supported this as well.

**Comment by jonan** [comment]
This is already implemented and will be available in the next release :wink: 
You can take a look at the [CHANGELOG.md](https://github.com/jonan/ForkHub/blob/master/CHANGELOG.md)
