### ISSUE TITLE
Log in button in the login view

### ISSUE THREAD

**Issue by TheMolkaPL** [jonan/ForkHub#171]
The log in button in the login view is not displayed correctly. The button could be white instead.

![forkhub](https://cloud.githubusercontent.com/assets/4578571/14119215/666fa762-f5ed-11e5-8a98-0b3b15228438.png)

**Comment by jonan** [comment]
That's because the button is disabled until you enter your user and password.

Doesn't it turn white once you enter them?

**Comment by TheMolkaPL** [comment]
It became white when I've typed my username and password. Thank you!
