### ISSUE TITLE
Remove organization repository on account profile

### ISSUE THREAD

**Issue by dikiaap** [jonan/ForkHub#176]
Hmm, Why put organization repository on account profile?
Many repo I have on organization, when I switch to my repo, it's hard.

It's be good if remove that. Organization repo always available,  if switch to orgz profile.

**Comment by jonan** [comment]
In the home's repository tab you see all the repositories that are accessible to you.

https://developer.github.com/v3/repos/#list-your-repositories
> This includes repositories owned by the authenticated user, repositories where the authenticated user is a collaborator, and repositories that the authenticated user has access to through an organization membership.
