### ISSUE TITLE
Cannot login with my hundred character password and 2fa

### ISSUE THREAD

**Issue by amingilani** [jonan/ForkHub#177]
Hi

Trying to log in with my 100 character password, and 2fa enabled account gives me an error `Please enter a valid username & password` even though I know they're both entirely correct.

**Comment by jonan** [comment]
I've tried to change my password to a really long one and I get this error from GitHub:
> Password is too long (maximum is 72 characters)

How have you manage to set a 100 characters password?

**Comment by amingilani** [comment]
@jonan that is a wonderful question, and I can honestly tell you I don't know. I just counted, the password is 81 characters, which is weird. Wait, i'll try changing my password again and seeing if it works.

**Comment by amingilani** [comment]
@jonan, you're right! They set a maximum for some reason after I changed my password last time. That's odd!

**Comment by amingilani** [comment]
I changed my password, maxed it to 72 characters, and was now able to sign in! Thanks @jonan
