### ISSUE TITLE
No issues visible

### ISSUE THREAD

**Issue by malenki** [jonan/ForkHub#178]
When looking at "issues" I see in neither tab anything. Either I am unable to handle the app correctly or it has a bug.
ForkHub runs here on Android 4.4.2.
PS: Not even this issue added using ForkHub is visible in the app. This postscript I added using my desktop box + browser.

**Comment by jonan** [comment]
Is this the same as #106?

**Comment by malenki** [comment]
Yes. Apologies for not looking first…
