### ISSUE TITLE
Username autocomplete

### ISSUE THREAD

**Issue by julenpardo** [jonan/ForkHub#199]
Hello,

I think that it would be nice to have an autocomplete for the usernames, specially in the issues, as the web version does, when you start writing an username with `@`. It's nice to send pings to the implied people in the issue, that are not watching it.

Zorionak lan bikainagatik!

**Comment by jonan** [comment]
Eskerrik asko Julen!

Anyway, this issue is dupe #55 :wink:

**Comment by julenpardo** [comment]
Oops, sorry, I searched for similar users only with "autocomplete".
