### ISSUE TITLE
(own) News page options

### ISSUE THREAD

**Issue by licaon-kter** [jonan/ForkHub#207]
Right now the app opens to (my own?) News page saying "no news" **and** popping up a toast saying "Not found (404)".

Can this news page be (optionally) changed with the Notifications page where (at least) I have _new_ stuff?

**Comment by jonan** [comment]
Sorry, but I don't really like this idea, we do the same thing as GitHub does.

**Comment by licaon-kter** [comment]
Looks like it started working after a while anyway. Thanks.
