### ISSUE TITLE
News only up to July 12, 2016 is visible

### ISSUE THREAD

**Issue by DavidGriffith** [jonan/ForkHub#209]
In the last few hours something happened to cause both Forkhub and the original unsupported Github app to not display any news newer than July 12, 2016.

**Comment by MasterOdin** [comment]
This is a Github problem and not the app.

From the (Github twitter)[https://twitter.com/githubstatus?lang=en&lang=en] 20 minutes ago:

>     We are continuing to rebuild timelines after restoring a core data service. 
>     Users may see missing events until this operation completes.

(with a core service going down like 3 hours ago or so)
