### ISSUE TITLE
List all milestones, list issues from milestone 

### ISSUE THREAD

**Issue by Nowaker** [jonan/ForkHub#211]
Teams organize issues into milestones. It'd be good to open a list of milestones, then click on  milestone and get a list of issues in the particular milestone.

**Comment by jonan** [comment]
You can already do that using the issue filter, and you can even bookmark the milestone for quick access. Isn't that enough?

**Comment by Nowaker** [comment]
I don't see an option to filter issues by any means, including milestones.

**Comment by nwalters512** [comment]
Scroll to the Issues tab, hit the menu overflow button, there should be an option to filter there.
