### ISSUE TITLE
feature request: install on SD card

### ISSUE THREAD

**Issue by carnicer** [jonan/ForkHub#216]
Hello, thanks for forking/creating this app. I have what (I believe) should be a simple and minor feature request. Would it be possible to make the app installable on the SD card? This way that it can free up space on the device internal storage, which can become quite full specially in not-that-new and powerful devices.
If that is feasible and OK with the project policies, I would be glad to try to contribute the code. In that case I'd appreciate if somebody points me to a solution since I do not have experience developing android apps.

**Comment by mprins** [comment]
it should be sufficient to set the `android:installLocation` in the manifest file to `auto`
see: https://developer.android.com/guide/topics/manifest/manifest-element.html#install

**Comment by jonan** [comment]
We've tried this already, but unfortunately it's not possible for this app.

PocketHub/PocketHub#90
PocketHub/PocketHub#479
