### ISSUE TITLE
F-Droid integration

### ISSUE THREAD

**Issue by AlphaOmega3** [jonan/ForkHub#218]
Add the ability to read installed app from F-Droid and add an GitHub corresponding page in a ForkHub setting/menu for view informations like source code, problems, ecc.

**Comment by TheMolkaPL** [comment]
#218

**Comment by jonan** [comment]
Sorry, I don't understand your request. Could you please explain it in more detail?

**Comment by AlphaOmega3** [comment]
Add, in the menu, the section "installed apps" with corresponding links to issues, source code, ecc

**Comment by jonan** [comment]
AFAIK there is no way for me to know what apps are installed in your device, and even if I could get the list, there's no way to know which is the corresponding repository in GitHub.

**Comment by AlphaOmega3** [comment]
Ok, thanks anyway
