### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by liach** [jonan/ForkHub#235]
1. Loading of issues fail too fast; when opening issues again, it succeed to load.
2. Forkhub cannot load pulls with review comments, as I have tried.

**Comment by alex-ter** [comment]
I see this after the latest update as well. Using both my WiFi and 3G links, which worked flawlessly before, are now timing out in exavtly the manner described. First attempt to open results in "loading issue failed", the second one displays the PR description, but not comments, the comments section has the rotating icon with the octocat, which never ends.

**Comment by jonan** [comment]
I just uploaded a new version that should fix the issue. Please give it a try and report back if it's still crashing.

Thanks!

**Comment by liach** [comment]
Fix confirmed. Thanks.

**Comment by alex-ter** [comment]
It also works for me, thanks @jonan and thumbs up for quick fix!
