### ISSUE TITLE
Nag screen advertising Play Store

### ISSUE THREAD

**Issue by Natureshadow** [jonan/ForkHub#246]
ForkHub just nagged me with some stupid popup telling me to rate it in something called a Play Store, which I do not even have.

Please remove that nag screen. Above all, please remove the advertisement for some proprietary spyware.

**Comment by jonan** [comment]
Most of the users download the app from the Play Store and asking them to rate it helps distribution, which in turn helps attracting new contributors, and this benefit all of us.

We only displays two dialogs, one to rate the app in the Play Store and one to star the repository here in GitHub, and each dialog is shown only once. If you dismiss or cancel the dialog you wont see it again, so it wont bother you again.

**Comment by Natureshadow** [comment]
How do you know that "most people" do that?

You also coule easily check for the Play Store being available before showing the nag screen.

**Comment by jonan** [comment]
> You also coule easily check for the Play Store being available before showing the nag screen.

This would be a valid solution. It's not really in my priority list but PRs are welcome :wink:
