### ISSUE TITLE
Display back links to issues that have noted this issue

### ISSUE THREAD

**Issue by Nashev** [jonan/ForkHub#26]
List of issues that links to this issue is very useful in Web interface. Please show the same in app

**Comment by jonan** [comment]
Unfortunately the API doesn't provide that information [1], so we can't implement it.
We already show all the issue events the API supports.

[1] https://developer.github.com/v3/issues/events/

**Comment by Nashev** [comment]
Yesterday I've sent suggestion

"Issue event for case where issue was referenced in other issue. Web
interface display this kind of back references and this are very useful.
But issue events api does not provide such information. Please add them"

to support@github.com and today have an answer:

"I agree that would be useful -- I'll pass your suggestion to the API team
to consider, but can't make any promises about if/when this might be
available. Thanks for expressing interest!"

**Comment by jonan** [comment]
Awesome!
Please ping this issue if you get any response.

**Comment by jonan** [comment]
Done!
