### ISSUE TITLE
Please Add a Dark Theme

### ISSUE THREAD

**Issue by ImSeth** [jonan/ForkHub#261]
Would you please add an option for a dark theme in Forkhub? This would be very useful for people who suffer from migraines, are photophobic, or who work in dark environments.
I am working on a project to list apps that support dark themes (https://imseth.github.io/Dark-Theme-Everywhere/). If you add a dark theme, I will be glad to add Forkhub to my list.
Thank you.

**Comment by jonan** [comment]
Duplicate #112
