### ISSUE TITLE
Dismissed reviews displayed incorrectly

### ISSUE THREAD

**Issue by liach** [jonan/ForkHub#277]
Browse CovertJaguar/Railcraft#486 on Forkhub and you will find my dismiss of my review displayed only with my username and the date.

**Comment by liach** [comment]
![screenshot_2017-03-21-11-29-02-28](https://cloud.githubusercontent.com/assets/7806504/24165734/71d4c146-0e2e-11e7-9fcb-da3f3a69a20f.png)

**Comment by jonan** [comment]
Thanks!
