### ISSUE TITLE
Toolbar image

### ISSUE THREAD

**Issue by saran2020** [jonan/ForkHub#311]
There is no space between the image of the user and the text in the action bar. I feel the image is not necessary there, or else there should be a padding there to make it look good.

**Comment by jonan** [comment]
You're right, the image looks odd and I've been thinking on improving it or removing it for a while now.

I'll look into it.

**Comment by DevBonBon** [comment]
+1 for removing the image from other than the main repository view. Things like pull request, commits, replies, etc. can do without it, as it might cut out the title text.
