### ISSUE TITLE
Issue: Commit from chrome showing as Gist

### ISSUE THREAD

**Issue by saran2020** [jonan/ForkHub#314]
When we open a commit in Google chrome and use the share option in that to open with ForkHob it is creating a Gist, instead of opening commit view. But when I install this app `https://play.google.com/store/apps/details?id=com.tasomaniac.openwith&hl=en` and then use it to open with ForkHub, it's working fine.

**Comment by ildar** [comment]
That's the normal difference between "sharing" and "opening". IMHO.

**Comment by jonan** [comment]
Chrome's share option is not meant for opening links in other apps.
This is expected behaviour.
