### ISSUE TITLE
Not all search results are shown

### ISSUE THREAD

**Issue by KOLANICH** [jonan/ForkHub#327]
When I search through ForkHub I get incomplete search results. When I know the issue I look for I have to narrow search request. When I need to see whole results, I have to use web interface.

**Comment by licaon-kter** [comment]
/duplicate of #326

You did search before posting, right? :) :)

**Comment by KOLANICH** [comment]
Don't you think that ```Search finds nothing``` is a bit different from "search finds something, but not the everything it must find"?

**Comment by licaon-kter** [comment]
My description might be incomplete indeed. Thanks

/still duplicate though

**Comment by jonan** [comment]
Lets close this issue and leave #326
