### ISSUE TITLE
Commits in wrong order

### ISSUE THREAD

**Issue by sedrubal** [jonan/ForkHub#38]
I detected, that the order of some commits is wrong. They aren't sorted by their date.

**Comment by sedrubal** [comment]
Same as in [github/android #420]( https://github.com/github/android/issues/420)

**Comment by jonan** [comment]
Commits shouldn't be sorted by date in git.
They are sorted following the tree, which is not necessarily chronological.

**Comment by sedrubal** [comment]
Ah ok
