### ISSUE TITLE
Can't close issues I opened on repos I don't own

### ISSUE THREAD

**Issue by chmac** [jonan/ForkHub#47]
I think I reported this upstream, but I guess the bug tracker has disappeared now, along with all the issues. Thanks again for your work on this fork, it's awesome to have usable GitHub on my phone. :-)

I noticed again today that when I click through to an issue I opened on somebody else's repo, I can't see an option to close it through the app. If I log in on mobile browser or desktop browser I have the close issue button next to the post a comment button. Would be awesome if I could do the same inside the app.

**Comment by turtledoveadmin** [comment]
You seem like great candidate to help me lol.... Please email me armstrongjason89@gmail.com I would so appreciate it just need help on one thing about the changelog
