### ISSUE TITLE
scala file parsing and string literal with """ """" delimiter

### ISSUE THREAD

**Issue by vmarrazzo** [jonan/ForkHub#60]
at first """ delimiter parsing does not identify closing """ so rest of file is handled as string literal

**Comment by jonan** [comment]
Can you link to an example?

**Comment by vmarrazzo** [comment]
https://github.com/vmarrazzo/compareBuild/blob/master/ch4ex1.scala

on my Samsung Galaxy S3 until line 66 I see correct parsing and code highlight after all code is highlighted like string literals

**Comment by jonan** [comment]
This was a bug in CodeMirror, updating it to the latest 4.x release fixed the issue.

Thanks!
