### ISSUE TITLE
Show starred repos

### ISSUE THREAD

**Issue by johanw666** [jonan/ForkHub#66]
Since version 0.9.1 (commit https://github.com/jonan/ForkHub/commit/c13fa394fba1f494242a1eb60da2063231d3170d) it doesn't show my starred repos anymore, and adding bookmarks seems impossible (I used the starring function for that, as Github itself describes the starring as a bookmark function). Please add an option to bookmark a repository or reverse this change.

**Comment by RandomlyKnighted** [comment]
I believe it was removed due to user feedback.  I also used it as a way to bookmark repos. Perhaps it would be a good idea to have a setting that let's user's turn it on or off. That way those who like it would be able to use it again.

**Comment by johanw666** [comment]
I found how to bookmark projects, however I can only bookmark the issue page of a project and it is stored locally on the device so it does not synchronise between my tablet and phone.

**Comment by jonan** [comment]
Bookmarks are _fast links_ to issue searches, what you want is the list of starred repos (just clearing this so we are in the same page).

I agree that showing the starred repos is a needed feature, but they shouldn't be shown in your repositories list, because people normally have a lot of starred projects and that kind of makes the repositories tab useless.

I'll try to create a new way of showing them.

**Comment by johanw666** [comment]
In that case, adding starred repo's in the list below Gists, Issue database and Bookmarks would be the easiest solution IMO.

**Comment by majekw** [comment]
I'm also missing starred repositories. I don't watch every my starred repositories to not clutter main feed, but sometimes I want to check what's happening in other projects and without showing starred repositories it's impossible (I don't fork everything around :-) ).
Please think about it - maybe at the beginning just add an option to turn it on/off as @RandomlyKnighted suggested?

**Comment by 0xf10e** [comment]
I like @johasnw666's suggestion. The sidebar is almost empty and is the 1st or 2nd place I looked for my starred repos.

**Comment by Tajnymag** [comment]
+1

**Comment by thilo-dual** [comment]
+1

**Comment by Tardis07** [comment]
Please add the "stared" option. It's really useful.

**Comment by SamClayton** [comment]
+1
