### ISSUE TITLE
We need to be able to zoom out farther

### ISSUE THREAD

**Issue by The-Fireplace** [jonan/ForkHub#67]
I want to be able to zoom further out, but the button is greyed out. I know, on the github website, it can't zoom out any further either, but I want to be able to on the app, at least.

**Comment by Parker8283** [comment]
:+1: This was a feature in the last version of the app pushed out to the Play Store by GitHub themselves. Would be nice to have this back.

**Comment by henengel** [comment]
+1

**Comment by jonan** [comment]
Fixed in https://github.com/jonan/ForkHub/commit/213f3bdbe280fbd98ca90a4262a5212dc9c9c0d6
