### ISSUE TITLE
app won't open with android 4.2.2

### ISSUE THREAD

**Issue by ancho85** [jonan/ForkHub#69]
this is an specific situation with jellybean related with appcompat-v7.
More details can be found at https://stackoverflow.com/questions/26657348/appcompat-v7-v21-0-0-causing-crash-on-samsung-devices-with-android-v4-2-2

the workaround to this is to set a proguard rule
-keep class !android.support.v7.internal.view.menu.**,android.support.v7.** {*;}

**Comment by jonan** [comment]
I've increased the minimum supported version to Android 4.4 for new releases, so I don't think this is going to be fixed.

Sorry.
