### ISSUE TITLE
Reverse sorting of version-branches and -tags

### ISSUE THREAD

**Issue by danez** [jonan/ForkHub#72]
Like the github site itself it would be nice if the newer versions show up first.

On the other hand the app also shows branches of pull-requests in the branch/tag chooser. Is that intended behavior? Same for `notes/github-comments` which seems to be a github internal branch.

**Comment by jonan** [comment]
I fixed the weird branches appearing in the chooser. Thanks for reporting!

On the other hand, sorting is not that simple as the API returns the list of references in alphabetical order, not by date. I'll try to do a few tests to see if I can improve the current situation.
