### ISSUE TITLE
Open github link in the app

### ISSUE THREAD

**Issue by ADTC** [jonan/ForkHub#8]
Referencing github/android#525 ...

> If you click on a link to github, you can select github as the default application but it still opens up in the browser. Have it open up in the app which will allow you to bypass needing to authenticate again. - memphis518

> Just encountered this. Any update? I'm developing an app where I added a 'Report an issue' option that redirects the user to the GitHub issue tracker. Since I have GitHub app installed, I get both the browser and the GitHub app as options to process the link. But when I select GitHub it just opens the browser (which makes the GitHub option redundant). - ADTC

**Comment by jonan** [comment]
I'm tracking the progress with links in #93.

Please comment on that issue if you want to add any link.
