### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by sedrubal** [jonan/ForkHub#88]
ForkHub uses a very custom design. Do you want to use a more material design respecting the material design guidelines?

**Comment by jonan** [comment]
Are you talking about the Play Store version?

In the `master` branch you should see quite a few Material Design elements.
I hope to have a new version ready this week :wink:

**Comment by jonan** [comment]
You can take a look at the [CHANGELOG](https://github.com/jonan/ForkHub/blob/master/CHANGELOG.md) to see what's going to be included in the next version.

**Comment by sedrubal** [comment]
Oooh great :smile: I'm looking forward the release

**Comment by sedrubal** [comment]
:+1:
