### ISSUE TITLE
Loading icon doesn't rotate

### ISSUE THREAD

**Issue by RandomlyKnighted** [jonan/ForkHub#92]
In the new UI, when scrolling to the bottom of the list you will see the Loading text with an icon. In the old UI, this icon would rotate so that you knew it was still downloading the content. Now it remains stationary, which makes it look like the app may have frozen. It'd be nice if this rotated again to avoid confusion.

Edit: Other than this minor issue I love the new UI!!!

**Comment by jonan** [comment]
I can't reproduce this on any of my devices and I haven't touched any code that might break it, so it's really weird.

Thanks for the good feedback!

**Comment by RandomlyKnighted** [comment]
Odd, last night I opened the app multiple times and it kept doing it. Now when I open the app it works fine. Thanks for following up on it.
