### ISSUE TITLE
Issue closed events don't show commit

### ISSUE THREAD

**Issue by fenhl** [jonan/ForkHub#95]
The website says that “user X closed this in commit Y” but ForkHub only says that the issue was closed by X.

**Comment by RandomlyKnighted** [comment]
The website also shows closed events that look like the following:

```jonan closed issue jonan/ForkHub#8```

The app says

```jonan closed issue 8 on jonan/ForkHub```

**Comment by jonan** [comment]
Thanks for the feedback!

@fenhl I guess you're talking about issue events aren't you?

@RandomlyKnighted news feed events don't show the commit closing the issue.
